emp=input("whats your employee name ")
eno=input("what is your eno of employee ")
esal=input("what is your sallery of employee ")
address=input("what have address of your employee ")
marraige=bool("your empolee did have marraige or not [True|False] ")
print("my name is ",emp)
print("my eno is ",eno)
print("my saller is ",esal)
print("my address is ",address)
print("this employee have marraige or not ")
